config/routes.rb
Rails.application.routes.draw do



  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :public, path: "" do
  # 以下、customers
    get 'customers/edit' => 'customers#edit', as: 'edit_mypage'
    patch 'customers' => 'customers#update'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/check' => 'customers#check', as: 'check'
    patch 'customers/withdraw' => 'customers#withdraw'
  # 以下、addresses
    resources :addresses, only: [:index,:create, :edit, :update, :destroy]
  # 以下、items
    resources :items, only: [:index, :show]
    get '/search' => 'items#search', as: 'search'
  # 以下、genres
    resources :genres, only: [:show]
  # 以下、cart_items
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  # 以下、orders
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
  end




  namespace :admin do
  # 以下、genres
    resources :genres, only: [:index,:create, :edit, :update]
  # 以下、items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  # 以下、customers
    resources :customers, only: [:index, :show, :edit, :update]
  # 以下、homes(注文履歴一覧)
    get '/' => 'homes#top'
  # 以下、orders（顧客別注文履歴一覧、注文履歴詳細、注文ステータス・着手状況の更新）
    resources :orders, only: [:index, :show, :update]
  # 以下、order_details（製作ステータスの更新）
    resources :order_details, only: [:update]
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  # ０＝クレジットカード、１＝銀行振込
  enum payment_method: { credit_card: 0, transfer: 1 }
  # ０＝入金待ち、１＝入金確認、２＝製作中、３＝発送準備中、４＝発送済み
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }




end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    # @order = Order.find(params[:order][:customer_id])
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @total_price = @order.total_payment - @order.shipping_cost
    @order_details = OrderDetail.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h1>Admin::Orders#index</h1>

<% @orders.each do |order| %>
<h3><%= order.customer.last_name + order.customer.first_name %></h3>
<% end %>





<%= paginate @orders %>

<!--# 以下、Orderのカラムまとめ-->
<!--  #  customer_id＝会員ID、postal_code＝郵便番号、address＝住所、name＝宛名、shipping_cost＝送料、-->
<!--  #  total_payment＝請求額、payment_method＝支払方法、status＝受注ステータス-->

<!--# 以下、OrderDetailのカラムまとめ-->
<!--  #  item_id＝商品ID、order_id＝注文ID-->
<!--  #  price＝購入時価格（税込）、amount＝数量、making_status＝製作ステータス-->

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    
    <h4 class="d-flex align-items-center m-3" style="background-color: #EEEEEE;">注文履歴詳細</h4>
  </div>

<table class="table table-borderless">
    <tr>
        <th>購入者</th>
        <td><%= link_to admin_customer_path(@order.customer.id) do %>
            <span class="text-dark"><%= @order.customer.last_name + @order.customer.first_name %></span>
            <% end %>
        </td>
    </tr>
    <tr>
        <th>注文日</th>
        <td><%= l @order.created_at, format: :YMD %></td>
    </tr>
    <tr>
        <th>配送先</th>
        <td><%= '〒' + @order.postal_code + ' ' + @order.address %></br>
            <%= @order.name %></td>
    </tr>
    <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
    </tr>

    <tr>
        <th>注文ステータス</th>
    <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
        <td><%= f.select :status, Order.statuses_i18n.invert, prompt: "#{@order.status}" %></td>
        <td><%= f.submit '更新', class: "btn btn-success" %></td>
    <% end %>
    </tr>
</table>
    </div>
</div>



<div class="row">
<div class="col-9">
<table class="table">
    <tr style="background-color: #EEEEEE;">
        <th class="align-middle">商品名</th>
        <th class="align-middle">単価（税込）</th>
        <th class="align-middle">数量</th>
        <th class="align-middle">小計</th>
        <th class="align-middle">製作ステータス</th>
        <th colspan="3"></th>
    </tr>
<% @order_details.each do |order_detail| %>
    <% if @order.id == order_detail.order_id %>
    <tr>
        <td class="align-middle"><%= order_detail.item.name %></td>
        <td class="align-middle"><%= order_detail.item.add_tax_price %></td>
        <td class="align-middle"><%= order_detail.amount %></td>
        <td class="align-middle"><%= order_detail.subtotal.round.to_s(:delimited) %></td>
    <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :update do |f| %>
        <td class="align-middle"><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, prompt: "#{order_detail.making_status}" %></td>
        <td class="align-middle"><%= f.submit "更新", class: "btn btn-success" %></td>
    <% end %>
    </tr>
    <% end %>
<% end %>
</table>
</div>

<div class="col-3 d-flex align-items-end justify-content-end">
<table style="float:right;">
    <tr>
        <th>商品合計</th>
        <td><%= @total_price.round.to_s(:delimited) %>円</td>
    </tr>
    <tr>
        <th>送料</th>
        <td><%= @order.shipping_cost.round.to_s(:delimited) %>円</td>
    </tr>
    <tr>
        <th>請求金額合計</th>
        <td><%= @order.total_payment.round.to_s(:delimited) %>円</td>
    </tr>
</table>
</div>
</div>
<!--# 以下、Orderのカラムまとめ-->
<!--  #  customer_id＝会員ID、postal_code＝郵便番号、address＝住所、name＝宛名、shipping_cost＝送料、-->
<!--  #  total_payment＝請求額、payment_method＝支払方法、status＝受注ステータス-->

<!--# 以下、OrderDetailのカラムまとめ-->
<!--  #  item_id＝商品ID、order_id＝注文ID-->
<!--  #  price＝購入時価格（税込）、amount＝数量、making_status＝製作ステータス-->