config/routes.rb
Rails.application.routes.draw do



  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :public, path: "" do
  # 以下、customers
    get 'customers/edit' => 'customers#edit', as: 'edit_mypage'
    patch 'customers' => 'customers#update'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/check' => 'customers#check', as: 'check'
    patch 'customers/withdraw' => 'customers#withdraw'
  # 以下、addresses
    resources :addresses, only: [:index,:create, :edit, :update, :destroy]
  # 以下、items
    resources :items, only: [:index, :show]
    get '/search' => 'items#search', as: 'search'
  # 以下、genres
    resources :genres, only: [:show]
  # 以下、cart_items
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  # 以下、orders
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
  end




  namespace :admin do
  # 以下、genres
    resources :genres, only: [:index,:create, :edit, :update]
  # 以下、items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  # 以下、customers
    resources :customers, only: [:index, :show, :edit, :update]
  # 以下、homes(注文履歴一覧)
    get '/' => 'homes#top'
  # 以下、orders（顧客別注文履歴一覧、注文履歴詳細、注文ステータス・着手状況の更新）
    resources :orders, only: [:index, :show, :update]
  # 以下、order_details（製作ステータスの更新）
    resources :order_details, only: [:update]
  end


end

app/models/address.rb
class Address < ApplicationRecord


  belongs_to :customer


  def address_display
    '〒' + postal_code + '' + address + '' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end


  def my_address
    '〒' + postal_code + ' ' + address
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true


end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def get_image(width,height)
   unless image.attached?
     file_path = Rails.root.join('app/assets/images/default-image.jpeg')
     image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg' 'image/webp' )
   end
   image.variant(resize_to_limit: [width,height]).processed
  end

  def add_tax_price
      (self.price * 1.1).round
  end

# Item内の検索機能
  def self.search(keyword)
    where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  # ０＝クレジットカード、１＝銀行振込
  enum payment_method: { credit_card: 0, transfer: 1 }
  # ０＝入金待ち、１＝入金確認、２＝製作中、３＝発送準備中、４＝発送済み
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  # ０＝着手不可, １＝製作待ち, ２＝製作中, ３＝製作完了
  enum making_status: { start_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    item.add_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
    redirect_to admin_genres_path
    else
    render :edit
    end
  end


  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    
    
    
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_deleted])
        devise_parameter_sanitizer.permit(:account_update, keys: [:email, :last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_deleted] )
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1 ">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand">
        <div class="container">
          <%= link_to '/' do %>
            <div class="navbar-brand p-4 text-dark">ながのCAKE</div>
          <% end %>
          <% if customer_signed_in? %>
            <div><%= flash[:notice]  = "ようこそ、#{current_customer.last_name}さん！" %></div>
          <% end %>
            <div class="row">
              <ul class="navbar-nav" style="position: absolute; top: 10px; right: 5px;">
<!--adminのログイン後メニュー-->
    <% if admin_signed_in? %>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "商品一覧", admin_items_path, class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "会員一覧", admin_customers_path, class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "注文履歴一覧", '/admin', class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-light'  %></li>
<!--customerのログイン後メニュー-->
    <% elsif customer_signed_in? %>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "マイページ", public_mypage_path , class: 'btn btn-light' %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "商品一覧", public_items_path, class: 'btn btn-light' %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "カート", public_cart_items_path, class: 'btn btn-light' %></li>
    <li class="nav-item" style="margin-right: 10px;"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-light' %></li>
<!--admin、customerのログイン前メニュー-->
    <% else %>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "About", about_path, class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "商品一覧", public_items_path, class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "新規登録", '/customers/sign_up', class: 'btn btn-light'  %></li>
    <li class="nav-item" style="margin-right: 30px;"><%= link_to "ログイン", '/customers/sign_in', class: 'btn btn-light'  %></li>
    <% end %>
              </ul>
            </div>

<!--Item内のワード検索機能（部分一致）-->
          <div><%= render 'public/items/search_list' %></div>
        </div>
      </nav>
    </header>

    <main class="h-100">
        <%= yield %>
    </main>

    <footer class="bg-dark pt-5 pb-4">
    </footer>
  </body>
</html>